### ISSUE TITLE
Abandoned or complete?

### ISSUE THREAD

**Issue by delaneyj** [customerio/esdb#6]
I was considering making a immutable blockchain for events when I stumbled upon you project.  The project has not seen much updating, for this kind of project that's either a really good thing or really bad.  What's the status, did it get used?

**Comment by jrallison** [comment]
Hey Delaney,

We still use this internally for isolated use-cases, but aren't actively moving forward with the data format, and I wouldn't recommend anyone use it :)

For us, it was more of an exploration for how to simply store and quickly read through TBs of immutable data without the overhead running an active database (i.e. sticking with flat files), and for that it solved our immediate pain points.
